controller:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: apps-internal-ingress
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: 10254
  ingressClassResource:
    controllerValue: k8s.io/ingress-nginx-internal
    name: nginx-internal


# Installation
#  helm upgrade -i ingress-nginx ingress-nginx/ingress-nginx-internal \
#  --namespace kube-system \
#  --values values.yml

# C02CF96TMD6R:nginx-controller alexr$ kubectl get -n kube-system service ingress-nginx-internal-controller -o yaml
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     meta.helm.sh/release-name: ingress-nginx-internal
#     meta.helm.sh/release-namespace: kube-system
#     service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
#     service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "10254"
#     service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
#     service.beta.kubernetes.io/aws-load-balancer-name: apps-internal-ingress
#     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#     service.beta.kubernetes.io/aws-load-balancer-scheme: internal
#     service.beta.kubernetes.io/aws-load-balancer-type: external
#   creationTimestamp: "2025-05-27T17:21:51Z"
#   finalizers:
#     - service.eks.amazonaws.com/resources
#   labels:
#     app.kubernetes.io/component: controller
#     app.kubernetes.io/instance: ingress-nginx-internal
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: ingress-nginx
#     app.kubernetes.io/part-of: ingress-nginx
#     app.kubernetes.io/version: 1.11.3
#     helm.sh/chart: ingress-nginx-4.11.3
#   name: ingress-nginx-internal-controller
#   namespace: kube-system
#   resourceVersion: "6122180"
#   uid: 06d1f588-b674-45b5-a5fc-ded324ea3cae
# spec:
#   allocateLoadBalancerNodePorts: true
#   clusterIP: 172.20.3.220
#   clusterIPs:
#     - 172.20.3.220
#   externalTrafficPolicy: Cluster
#   internalTrafficPolicy: Cluster
#   ipFamilies:
#     - IPv4
#   ipFamilyPolicy: SingleStack
#   loadBalancerClass: eks.amazonaws.com/nlb
#   ports:
#     - appProtocol: http
#       name: http
#       nodePort: 31733
#       port: 80
#       protocol: TCP
#       targetPort: http
#     - appProtocol: https
#       name: https
#       nodePort: 32143
#       port: 443
#       protocol: TCP
#       targetPort: https
#   selector:
#     app.kubernetes.io/component: controller
#     app.kubernetes.io/instance: ingress-nginx-internal
#     app.kubernetes.io/name: ingress-nginx
#   sessionAffinity: None
#   type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#       - hostname: apps-internal-ingress-72b4fbf875594228.elb.us-west-2.amazonaws.com