FROM nginx:1.28.0-perl


RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/conf.d/default.conf  /etc/nginx/conf.d/default.conf 



# Set not to use 80
RUN sed -i 's/listen       80;/listen       8021;/g' /etc/nginx/conf.d/default.conf
RUN sed -i '/listen  \[::\]:80;/d' /etc/nginx/conf.d/default.conf
RUN sed -i '/user  nginx;/d' /etc/nginx/nginx.conf

# For run as non-root
RUN     chown -R nginx:nginx /var/cache/nginx && \
        chown -R nginx:nginx /var/log/nginx && \
        chown -R nginx:nginx /etc/nginx/conf.d

RUN touch /var/run/nginx.pid && \
        chown -R nginx:nginx /var/run/nginx.pid

COPY html /usr/share/nginx/html

USER nginx:nginx


expose 8021
