apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: networktools
spec:
  selector:
    matchLabels:
      app: networktools
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: networktools
    spec:
      containers:
      - name: networktools
        image: jonlabelle/network-tools
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent

